language: ruby

before_script:
  - npm install -g karma
  - npm install -g karma-jasmine
  - npm install -g karma-phantomjs-launcher

script:
  - karma start karma.conf.js --single-run --browser PhantomJS
