language: ruby

before_script:
  - npm install karma
  - npm install karma-requirejs
  - npm install karma-phantomjs-launcher

script:
  - bundle exec rspec spec
  - node_modules/karma/bin/karma start karma.conf.js --single-run --browsers PhantomJS