language: ruby

before_script:
  - npm install karma
  - npm install karma-jasmine
  - npm install karma-requirejs
  - npm install karma-phantomjs-launcher

script:
  - node_modules/karma/bin/karma start karma.conf.js --single-run --browser PhantomJS
