language: ruby

before_script:
  - npm install karma
  - npm install bower
  - npm install karma-phantomjs-launcher
  - psql -c 'create database etf_test;' -U postgres
  - node_modules/bower/bin/bower install

script:
  - bundle exec rspec spec
  - node_modules/karma/bin/karma start karma/karma.conf.js --single-run --browsers PhantomJS